on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Action test
    steps:
      - uses: actions/checkout@v3

      - name: change tag
        uses: ./ # Uses an action in the root directory
        with:
          filename: test/values.yaml
          component_name: kubescape
          tag: 2232
      
      - run: cat values.yaml